name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test 
    - name: Build
      run: cargo build --release
    - name: Package artifact
      run: tar -czvf roman.tar.gz target/release/roman
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: roman
        path: roman.tar.gz
